app:
  name: configApp
  version: 2.3.1
  serverUrl:  localhost:8080
  serverName: configServer
  user:
    firstName: user
    lastName: demo
    userName: user@demo
    password: password
  countries:
    - UK
    - USA
    - Germany
    - Japan
